README.md, apps/cli/.eslintrc.json, apps/cli/package.json, apps/cli/src/lib/get-commands.ts, libs/report/ingestion/.eslintrc.json, libs/report/ingestion/README.md, libs/report/ingestion/jest.config.ts, libs/report/ingestion/package.json, libs/report/ingestion/project.json, libs/report/ingestion/src/index.ts, libs/report/ingestion/src/lib/ingestion-manifest.spec.ts, libs/report/ingestion/src/lib/ingestion-prompt.spec.ts, libs/report/ingestion/src/lib/ingestion.ts, libs/report/ingestion/src/lib/prompts.ts, libs/report/ingestion/src/lib/queries.ts, libs/report/ingestion/src/lib/send-manifest.ts, libs/report/ingestion/src/lib/types.ts, libs/report/ingestion/tsconfig.json, libs/report/ingestion/tsconfig.lib.json, libs/report/ingestion/tsconfig.spec.json, package-lock.json, package.json, tsconfig.base.json
This features allows customer to send their package.json.
Bikeshedding or error messages, prompts, naming welcome 😄
=> feat: ingestion

.vscode/settings.json, src/commands/scan/eol.ts, src/service/eol/eol.svc.ts, src/service/eol/eol.types.ts, src/service/eol/eol.ui.ts, src/service/nes/modules/sbom.test.ts, src/service/nes/modules/sbom.ts, src/service/nes/nes.client.ts, src/service/nes/types.ts, test/hooks/prerun/CommandContextHook.test.ts, types/cdxgen.d.ts
- Fix `NesClient.scan.sbom` type
- Remove `any` where feasible.
- Add explicit return types where feasible
- Connect `Line` type with `ScanResultComponent` type
=> chore: clean up types and fix linting errors

.vscode/settings.json, src/service/eol/eol.svc.ts, src/service/line.ts, test/commands/scan/eol.test.ts, test/service/line.test.ts
This PR was started due to this previous PR comment: https://github.com/herodevs/cli/pull/91#discussion_r1994903119
If details don't exist for a given Component (i.e., we don't have XEOL data), then we'll throw a debug warning and filter out those results from Lines.
Additionally:
- create getStatusFromComponent method to standardize how a status is derived from component info
- add specs for the same
=> feat: filter from `prepareRows` where not details

src/service/eol/eol.svc.ts, test/service/eol.svc.test.ts, test/utils/mocks/scan-result-component.mock.ts
This PR is a follow-up to a comment from a previous [PR](https://github.com/herodevs/cli/pull/92#discussion_r1995667475).
I wrote the specs for the previous implementation in the first commit. In the second commit I refactored the prepareRows method and ensured that the specs still passed.
Please see commit messages for more details.
=> perf: refactor prepare-rows method to use for loop

.github/workflows/release.yml, packages/cli-darwin-arm64/package-lock.json, packages/cli-darwin-arm64/package.json, packages/cli-linux-x64/package-lock.json, packages/cli-linux-x64/package.json, packages/cli-win32-x64/package-lock.json, packages/cli-win32-x64/package.json, packages/cli/package.json
This PR has a few fixes that get the CI to run successfully:
- adds a dot in front of the artifact directory when running npm publish[1]
- adds `--no-xz` to the windows pack command: otherwise npm publish fails for windows.[2]
- changes the GitHub release files to `artifacts/*.tar.gz`: otherwise creating a GitHub release fails.[3]
- switched to `draft: true` for the GitHub release action
- updates the package version numbers to `1.0.0-beta`
There are also a few changes that seem reasonable but may not be required
- sets the `registry-url` in the `publish-cli` step
- switch the `NODE_AUTH_TOKEN` from `HD_CLI_NPM_TOKEN` to `GITHUB_TOKEN` (does the HD one even exist anymore?)
This PR resulted in a draft GitHub Release getting created. I manually deleted it. The version was missing although …
=> chore: fix package versions and add token 

.github/workflows/ci.yml, .github/workflows/release.yml, .vscode/settings.json, package-lock.json, package.json, packages/cli-darwin-arm64/package-lock.json, packages/cli-darwin-arm64/package.json, packages/cli-linux-x64/package-lock.json, packages/cli-linux-x64/package.json, packages/cli-win32-x64/package-lock.json, packages/cli-win32-x64/package.json, packages/cli/package.json, src/commands/scan/eol.ts, src/config/update.ts, src/hooks/init/update.ts, test/commands/scan/eol.test.ts
In this PR:
- install @oclif/plugin-update for auto-updating.[1]
- set version to 1.0.0-beta.0.[1]
- add inputs to release workflow for release channel and dry-run
Please see this discussion update about beta channel releases.[2]
[1]https://www.atatus.com/blog/release-beta-nodejs-package/
[2]https://github.com/herodevs/cli/issues/104#issuecomment-2738098416
=> feat: add auto-update feature

README.md, src/api/queries/nes/sbom.ts, src/api/types/nes.types.ts, src/commands/scan/eol.ts, src/service/eol/eol.svc.ts, src/service/line.svc.ts, src/service/nes/nes.svc.ts, test/service/eol.svc.test.ts, test/service/line.svc.test.ts, test/utils/mocks/scan-result-component.mock.ts
This PR ensures that the monorepo api is the source of truth for the status of a given purl (EOL, UNKNOWN, LTS, or OK).
The `scan eol` command is still gated so it cannot be used in production. We will enable that command once the api is deployed to the monorepo.
=> feat: move eol status handling to backend

src/api/client.ts, src/commands/report/committers.ts, src/commands/report/purls.ts, src/commands/scan/sbom.ts, src/service/error.svc.ts
Leverage oclif's built-in `this.error` functionality where feasible.
Add a few utility methods for getting the `message` out of Errors more easily.
=> feat: create error service

README.md, src/commands/report/purls.ts, src/commands/scan/eol.ts, src/service/purls.svc.ts, test/service/purls.svc.test.ts
This flag allows eol scan to directly consume a list of purls to send to our api.
Users can still generate an sbom or use an existing sbom to get a list of purls.
This feature allows `scan eol` to be useable by clients who want to derive a list of purls using a method besides cyclonedx sboms.
This feature also allows `scan eol` to `dog food` the output of `report purls -s`.
=> feat: add purls flag to eol scan

src/service/eol/cdx.svc.ts
The cdxgen createBom function uses debug logging unless the NODE_ENV is production.
We can (and should) revisit setting NODE_ENV appropriately to manage logs.
=> chore: revert to async import to fix logs

README.md, package-lock.json, package.json
When using S3 buckets, oclif claims that all we have to do to get auto-updates is add the `oclif/plugin-update` plugin:
> Autoupdater
> These tarballs as well as the installers below can be made autoupdatable by adding the @oclif/plugin-update plugin. 
> Just add this plugin and the CLI will autoupdate in the background or when mycli update is run.
> 
> If you don't want to use S3, you can still run oclif pack and it will build tarballs. To get the updater to work, set 
> oclif.update.s3.host in package.json to a host that has the files built in ./dist from oclif pack. This host does not 
> need to be an S3 host. To customize the URL paths, see the S3 templates in @oclif/core.
https://oclif.io/docs/releasing/#autoupdater
=> chore: install auto updater plugin

.github/workflows/manual-release.yml
The previous workflow failed to exclude the tarballs from the npm publish step. This PR fixes that issue.
=> chore: ee/exclude tarballs from npm

.github/workflows/manual-release.yml
This PR fixes a few quirks with how we were uploading to s3:
- Ensures we use a short commit hash in the `oclif promote --sha=<short-hash>` to meet oclif's expectations
- Ensure the darwin and linux tarballs don't contain the contents of the other tarballs by using `--parallel`
- Ensure the channel used by oclif can be beta even if we're _not_ doing a dry run
- [Green CI Run](https://github.com/herodevs/cli/actions/runs/14275524079)
- Screenshot showing beta channel in s3
=> chore: fix how we set channels in s3

package-lock.json, package.json, src/api/nes/nes.client.ts, src/api/queries/nes/sbom.ts, src/api/types/nes.types.ts, src/commands/scan/eol.ts, src/service/eol/eol.svc.ts, src/service/nes/nes.svc.ts, src/ui/eol.ui.ts, test/ui/eol.ui.test.ts, test/utils/mocks/scan-result-component.mock.ts
This PR does two things:
1. Replace cli-table3 with pre-existing dependency (@oclif/table)
2. Add vulnCount to the table output.
We are waiting on a backend deployment before we actually have vulnCount numbers. A PR is open with that update. Until then, the vulnCount property in the gql query must be commented out.
As explained in the commit messages, I noticed that we already have a dependency on the @oclif/table package so I decided to reduce our dependencies and just use that instead of cli-table3.
=> feat: add vuln count to table output

src/service/purls.svc.ts, test/service/purls.svc.test.ts
I came across an error when running the tool and zero purls were generated. Instead of throwing an error in this case, we should handle it gracefully.
=> chore: improve error handling for purl files

bin/dev.js, bin/run.js, e2e/scan/eol.test.ts, package.json
When the user provides no arguments to the cli, by default it should run `scan eol-t`.
@marco-ippolito do not merge this even if it has two approvals. This is pointed to the release branch. I'm waiting on the release branch to be approved so I can merge that branch and deploy the tag.
=> feat: run `scan eol -t` by default

bin/dev.js, bin/main.js, bin/run.js, e2e/scan/eol.test.ts
Previously, the command `npx @herodevs/cli@beta --json` would fail.
With this change, users pass in flags and apply them to the `scan eol` command by default.
=> feat: accept scan eol flags by default

src/hooks/npm-update-notifier.ts, test/hooks/npm-update-notifier.test.ts
This PR also (i) ensures that the update notifier checks for updates every time _if_ the user is on a beta version, and (ii) adds debug logging.
https://github.com/orgs/neverendingsupport/projects/16/views/3?pane=issue&itemId=110305060&issue=neverendingsupport%7Cdata-and-integrations%7C20
=> feat: log update-notifier message to stdout

.envrc.example, .github/workflows/ci.yml, .github/workflows/dry-run.yml, .github/workflows/manual-release.yml, .gitignore, bin/dev.js, e2e/scan/eol.test.ts, src/api/nes/nes.client.ts
Previously, the e2e tests were being run against prod. This was not the intention. Process env variables were set in multiple places:
- bin/run.js
- bin/dev.js
- eol.test.ts
- src/config/constants.ts
This allowed for the `config` and the `process.env` vars to get out of sync, which caused unexpected results for the value of those vars during e2e tests.
This commit consolidates to the `config` as the source of truth for env vars. I've deleted the attempts to set env vars everywhere else.
For convenience, I've added a `.envrc.example` file showing how to set development vars. You can use `direnv allow` to load vars in a .envrc file.[1]
Recent changes to the api is causing the e2e test to be flaky. The api team is aware and working towards a resolution. Until then, I'm skipping the e2e spec …
=> fix: ensure e2e tests don't run against prod

README.md, src/api/types/nes.types.ts, src/commands/scan/eol.ts, src/ui/shared.ui.ts
Partial change for https://github.com/neverendingsupport/data-and-integrations/issues/95. Does not close it yet because we need to make the same change in the report card too.
=> chore: rename `SUPPORTED` to `EOL_UPCOMING`

src/commands/scan/eol.ts
Previously, the id was missing:
=> fix: ensure url is correct on vscode terminal

package-lock.json, package.json, src/commands/scan/eol.ts, src/commands/scan/sbom.ts
Closes https://github.com/neverendingsupport/data-and-integrations/issues/118
https://github.com/user-attachments/assets/5e47720c-d12e-484a-a166-02a62e2b4b64
=> feat: add scan progress descriptions and loaders

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, ci/image.Dockerfile
Closes neverendingsupport/data-and-integrations#137
Closes neverendingsupport/data-and-integrations#138
Closes neverendingsupport/data-and-integrations#139
=> feat: publish eol-scan image
